env:
  global:
  - TMPDIR=/tmp
  - secure: AMYnrwhL/RQKKL0JUdLgTwdev9rn7fbShSVUEb+zBHgM173dxXLyCwDdW2+nRHksZ4WAIpfx60i+kH/7eilRTFvka4576c1TwH80JqTHy0UI9PZ941rY8NjNwPt9MlgoW8OajmHIMLDyeR1ft3ApMn6MyCj9+zMRZAOtB+pGGI9DXDmUniDn9589LJ8xCho6M0ZE/aBfA6i+SwbY/NrT7hhBH37xukZlgmB1gGDfiq/To9I/BS+R+eNDkWplcXJuGL42hor+M53/8d1eNDBgYwpjJwTJowc6lXOXkhk4tc/GwLhT+soHV52NTmJWxEJ9rJFDavKjqgW14nxBTe2WXvaKLGWzp7Dai8n4zrT2kaoxzO3deDScwqR2mvF/sZwiNRjzEkDcYIWG3Hv1clq+U6Q2t0ktcIzTCZ6U8vzRdJGYC5gVgpb6GXoqx4GTmGtq9u8nC+TKiIb0nBQCqh6UKzrtsamopueeS16NgkRruzrqfINJReMpJIS37UYp6E186A5JzrXnwNeOhDTWizWYOoIy41uzOTmUx4WT3TLiFnWkdJkCP3kH47Z8vcWW8jSFeFiZ8OAb+3/YQfZ2rj+cSfdQD5JjbgZTaPvzH7MvPqukRlvMLpVhKS7FtInsiAh7E70M79Eg8RMBIVwvNaY44/Q3/8aIP7+PPq7hSkZZLCc=
language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
install: true
sudo: false
before_script:
- git clone https://github.com/Cognifide/bobcat.git ${TMPDIR}/bobcat && cd ${TMPDIR}/bobcat
  && mvn clean install -DskipTests && cd ${TRAVIS_BUILD_DIR}
script: mvn versions:use-latest-versions versions:commit && mvn clean verify -DskipTests
after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git config user.name "travis"
- git config user.email "travis"
- "./updateBobcatVersion.sh"
